### ISSUE TITLE
All errors do not work

### ISSUE THREAD

**Issue by remo5000** [source-academy/js-slang#6]
Error given:

```
(node:59961) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at fmtError (/Users/vigneshshankar/workspace/cs1101s/slang/dist/repl.js:7:28)
    at promise.then (/Users/vigneshshankar/workspace/cs1101s/slang/dist/repl.js:20:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:59961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Expected: Nodes that outline the SourceError thrown.

**Comment by ningyuansg** [comment]
Can we close this since the repl was removed?
